baseurl: /
auto: true

markdown: rdiscount
pygments: false
paginate: 8
permalink: /:title
excerpt_separator: more

title: Seamaner.com
url: http://seamaner.com
duoshuo: seamaner
feed: /atom.xml
author_info: <a href="http://seamaner.com/">Seamaner</a>
